In [126]:
import numpy as np

arr1 = np.array([5,7,23,3])
arr2 = arr1

arr1 = 10
print(arr2)

arr2 = 2

print(arr1, arr2)

[ 5  7 23  3]
10 2

In [127]:
pref = np.array([[21, 32, 49, 34],
              [10, 38, 50, 13],
              [22, 13, 28, 23]])

print(pref)

[[21 32 49 34]
 [10 38 50 13]
 [22 13 28 23]]

In [128]:
# print the number of drink options
print()
# print the number of studies
print()

In [129]:
tea = np.array([21,10,22])
coffee = np.array([32,38,13])
soda = np.array([49,50,28])
juice = np.array([34,13,23])

# try to put them together as in previous array
stacked_preferences = np.stack((tea,coffee,soda,juice))
print(stacked_preferences)
print(stacked_preferences.shape)

[[21 10 22]
 [32 38 13]
 [49 50 28]
 [34 13 23]]
(4, 3)

In [130]:
# PARANTHETICALLY
# .T -- TRANSPOSE swaps rows and columns
stacked_preferences_transposed = stacked_preferences.T
print(stacked_preferences_transposed)
print(stacked_preferences_transposed.shape)

[[21 32 49 34]
 [10 38 50 13]
 [22 13 28 23]]
(3, 4)

In [131]:
# ANOTHER TRANSPOSE EXAMPLE
a = np.arange(6).reshape(2,3)

print(a)
print(a.sum(axis=0))
print(a.T)
print(a.T.sum(axis=1))
# NOW BACK TO REGULARLY SCHEDULED PROGRAMMING

[[0 1 2]
 [3 4 5]]
[3 5 7]
[[0 3]
 [1 4]
 [2 5]]
[3 5 7]

In [132]:
# before the transpose break, what we had didn't quite work. it added a new ROW dimension, put it together along the wrong axis
stacked_preferences = np.stack((tea,coffee,soda,juice),axis=1)    # axis = 1 does a column stack
print(stacked_preferences)

[[21 32 49 34]
 [10 38 50 13]
 [22 13 28 23]]

In [133]:
# equivalent to column_stack
stacked_preferences = np.column_stack((tea,coffee,soda,juice))
print(stacked_preferences)

[[21 32 49 34]
 [10 38 50 13]
 [22 13 28 23]]

In [134]:
# what if different data types? NumPy will upcast everything to a common data type
a = np.array([1, 2, 3])          # ints
b = np.array(["A", "B", "C"])    # strings

c = np.stack((a, b), axis=1)
print(c)

[['1' 'A']
 ['2' 'B']
 ['3' 'C']]

In [135]:
# great if just printing multiple arrays together side by side
print(np.stack((a,b),axis=1))

[['1' 'A']
 ['2' 'B']
 ['3' 'C']]

In [136]:
import pandas as pd

pref = np.array([[21, 32, 49, 34],
              [10, 38, 50, 13],
              [22, 13, 28, 23]])

pref_df = pd.DataFrame(
    pref,
    columns=["Tea","Coffee","Soda","Juice"],
    index=["Study A","Study B","Study C"]
)

print(pref_df)
print(type(pref_df))

         Tea  Coffee  Soda  Juice
Study A   21      32    49     34
Study B   10      38    50     13
Study C   22      13    28     23
<class 'pandas.core.frame.DataFrame'>

In [ ]:
print(pref_df.values)
print(type(pref_df))
print(type(pref_df.values))
print(pref_df.values.dtype)
#print(pref_df.values.shape)

[[21 32 49 34]
 [10 38 50 13]
 [22 13 28 23]]
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
int64
(3, 4)

# A DataFrame is a 2D table with
labeled columns and

labeled rows

(if you don't specify meaningful names, they default to indices)

In [187]:
print(pref_df.index)
print(pref_df.columns)
df = pd.DataFrame([[1,2],[3,4]])
print(df.index)
print(df.columns)

Index(['Study A', 'Study B', 'Study C'], dtype='object')
Index(['Tea', 'Coffee', 'Soda', 'Juice'], dtype='object')
RangeIndex(start=0, stop=2, step=1)
RangeIndex(start=0, stop=2, step=1)

In [ ]:
pref_df["Coffee"]   # in brackets, specify column name
# returns a series representing a column

Study A    32
Study B    38
Study C    13
Name: Coffee, dtype: int64

In [ ]:
print(type(pref_df["Coffee"])) 
#print(pref_df["Coffee"].shape)

<class 'pandas.core.series.Series'>
(3,)

# A Series is like a single labeled column.  AKA, a one dimensional labeled data.

In [ ]:
# to access row:
pref_df.loc["Study A"]

Tea       21
Coffee    32
Soda      49
Juice     34
Name: Study A, dtype: int64

In [154]:
print(type(pref_df.loc["Study A"]))

<class 'pandas.core.series.Series'>

In [ ]:
pref_df.loc[:,"Coffee"]  # loc thinks (rows, columns)

Study A    32
Study B    38
Study C    13
Name: Coffee, dtype: int64

In [141]:
pref_df.loc["Study B","Soda"]

np.int64(50)

In [142]:
pref_df.loc[["Study A","Study B"]]

         Tea  Coffee  Soda  Juice
Study A   21      32    49     34
Study B   10      38    50     13

In [143]:
pref_df.iloc[0]

Tea       21
Coffee    32
Soda      49
Juice     34
Name: Study A, dtype: int64

In [144]:
pref_df.iloc[:,1]

Study A    32
Study B    38
Study C    13
Name: Coffee, dtype: int64

In [145]:
pref_df.iloc[1,2]

np.int64(50)

In [160]:
total = pref_df.sum()
print(f"{total}\n")
print(type(total))

Tea        53
Coffee     83
Soda      127
Juice      70
dtype: int64

<class 'pandas.core.series.Series'>

In [161]:
total = pref_df.sum(axis=1)
print(f"{total}\n")
print(type(total))

Study A    136
Study B    111
Study C     86
dtype: int64

<class 'pandas.core.series.Series'>

In [148]:
print(pref_df.values.sum())
print(type(pref_df.values))

333
<class 'numpy.ndarray'>

In [ ]:
#THE NUMPY WAY
#participants_per_study = np.sum(pref,axis=1,keepdims=True)
# switching to other form to make it more like pandas
participants_per_study = pref.sum(axis=1,keepdims=True)
percent_by_row = (pref / participants_per_study * 100)
print(percent_by_row.round(1))

[[15.4 23.5 36.  25. ]
 [ 9.  34.2 45.  11.7]
 [25.6 15.1 32.6 26.7]]

In [ ]:
print(type(percent_by_row))
#print(percent_by_row.shape)
print(type(participants_per_study))
#print(participants_per_study.shape)

<class 'numpy.ndarray'>
(3, 4)
<class 'numpy.ndarray'>
(3, 1)

# NumPy uses shape; pandas uses labels

In [181]:
# NOW LET'S DO IT THE PANDAS WAY
participants_per_study_in_df = pref_df.sum(axis=1)  
# numpy is values without labels, so we needed keepdims to tell us if it was a row or column
# pandas returns a Series which includes a label, which tells it what's what
print(participants_per_study_in_df)

Study A    136
Study B    111
Study C     86
dtype: int64

In [175]:
percent_by_row_df = pref_df / participants_per_study_in_df
percent_by_row_df *= 100
print(percent_by_row_df.round(1))

         Coffee  Juice  Soda  Study A  Study B  Study C  Tea
Study A     NaN    NaN   NaN      NaN      NaN      NaN  NaN
Study B     NaN    NaN   NaN      NaN      NaN      NaN  NaN
Study C     NaN    NaN   NaN      NaN      NaN      NaN  NaN

# The Series labels are row labels
# DataFrame expects column labels for alignment
so it fails

In [188]:
print(type(percent_by_row_df))
#print(percent_by_row_df.shape)
print(type(participants_per_study_in_df))
#print(participants_per_study_in_df.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [ ]:
# TELL PANDAS TO DO IT ROW-WISE.
# axis = 0: match by row labels
percent_by_row_df = pref_df.div(participants_per_study_in_df, axis=0)
percent_by_row_df *= 100
print(percent_by_row_df.round(1))

          Tea  Coffee  Soda  Juice
Study A  15.4    23.5  36.0   25.0
Study B   9.0    34.2  45.0   11.7
Study C  25.6    15.1  32.6   26.7

In [ ]:
percent = pref_df.div(pref_df.sum(axis=1), axis=0) * 100

print(percent.round(1))

In [168]:
# IT DOESN'T QUITE MAKE SENSE THE OTHER WAY, BUT LET'S LOOK AT IT
pref_df.sum(axis=0)

Tea        53
Coffee     83
Soda      127
Juice      70
dtype: int64

In [169]:
pref_df / pref_df.sum(axis=0)

              Tea    Coffee      Soda     Juice
Study A  0.396226  0.385542  0.385827  0.485714
Study B  0.188679  0.457831  0.393701  0.185714
Study C  0.415094  0.156627  0.220472  0.328571

# DataFrame / Series
pandas tries to align Series with Columns by default, works here

In [ ]:
print(type(pref_df))
#print(pref_df.shape)
print(type(pref_df.sum(axis=0)))
#print(pref_df.sum(axis=0).shape)

<class 'pandas.core.frame.DataFrame'>
(3, 4)
<class 'pandas.core.series.Series'>
(4,)

In [184]:
print(pref_df / pref_df.sum(axis=0))   # works
print(pref_df / pref_df.sum(axis=1))   # wrong / weird

              Tea    Coffee      Soda     Juice
Study A  0.396226  0.385542  0.385827  0.485714
Study B  0.188679  0.457831  0.393701  0.185714
Study C  0.415094  0.156627  0.220472  0.328571
         Coffee  Juice  Soda  Study A  Study B  Study C  Tea
Study A     NaN    NaN   NaN      NaN      NaN      NaN  NaN
Study B     NaN    NaN   NaN      NaN      NaN      NaN  NaN
Study C     NaN    NaN   NaN      NaN      NaN      NaN  NaN

In [185]:
print(pref_df.div(pref_df.sum(axis=1), axis=0))  # correct

              Tea    Coffee      Soda     Juice
Study A  0.154412  0.235294  0.360294  0.250000
Study B  0.090090  0.342342  0.450450  0.117117
Study C  0.255814  0.151163  0.325581  0.267442

# To clarify:
In .sum(), axis = direction of collapse

In .div(), axis = direction of alignment

In [ ]:
# A SECOND LOOK FOR COMPARISON
pref = np.array([[21, 32, 49, 34],
              [10, 38, 50, 13],
              [22, 13, 28, 23]])

# ONE WAY TO CREATE A DATAFRAME, SEND IT A NUMPY ARRAY, A LIST OF COLUMN NAMES, A LIST OF INDEX (ROW) NAMES
pref_df = pd.DataFrame(
    pref,
    columns=["Tea","Coffee","Soda","Juice"],
    index=["Study A","Study B","Study C"]
)

In [ ]:
# ANOTHER WAY TO CREATE A DATAFRAME: SEND THE CONSTRUCTOR A DICTIONARY
# pandas DataFrames are heterogeneous across columns
df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "AQI": [72, 85, 60]
})

print(df.dtypes)

# ADDITIONAL CONSTRUCTOR VARIATIONS

In [ ]:
# similar to
dict1 = {}
dict1["Name"] = ["A", "B", "C"]
dict1["AQI"] = [72, 85, 60]

# can send that dictionay to constructor
df = pd.DataFrame(dict1)

In [ ]:
# create DataFrame out of rows:
df = pd.DataFrame([
    {"Name": "A", "AQI": 72},
    {"Name": "B", "AQI": 85},
    {"Name": "C", "AQI": 60}
])

In [162]:
# you can include row names, too, by adding index parameter
df = pd.DataFrame(
    {
        "Name": ["A", "B", "C"],
        "AQI": [72, 85, 60]
    },
    index=["Study A", "Study B", "Study C"]
)

print(df)

        Name  AQI
Study A    A   72
Study B    B   85
Study C    C   60

In [ ]:
# OR set it separately
df = pd.DataFrame(
    {
        "Name": ["A", "B", "C"],
        "AQI": [72, 85, 60]
    })
df.index = ["Study A", "Study B", "Study C"]
print(df)

In [ ]:
# OR EVEN
pd.DataFrame(
    {
        "Study A": {"Name": "A", "AQI": 72},
        "Study B": {"Name": "B", "AQI": 85}
    }
).T

In [ ]:
# can i specify column names?
df = pd.DataFrame(
    {
        ["A", "B", "C"],
        [72, 85, 60]
    },
    columns=["Name","AQI"]
)

print(df)

In [ ]:
# the above is NOT VALID.
# if you pass a dictionary, keys = column names
# if you want to use columns, data must NOT be a dict
# CAN use a list of lists (OR NUMPY ARRAY as in our first example)

df = pd.DataFrame(
    [
        ["A", 72],
        ["B", 85],
        ["C", 60]
    ],
    columns=["Name", "AQI"],
    index=["Study A", "Study B", "Study C"]
)
print(df)